# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Botangisi
email: botangisi@gmail.com
footer_description:
  en:
    Botangisi is a nonprofit organization with the aim to promote and develop
    digital training, focusing on accounting and international cooperation.
  fr:
    L'Association Botangisi est une organisation à but non lucratif, dont
    l'objectif est de promouvoir l'éducation numérique et collaborative, en
    mettant l'accent sur la comptabilité, les affaires et le contexte de la
    coopération internationale.
  it:
    L'Associazione Botangisi è un ente senza scopo di lucro, che ha come scopo
    quello promuovere la formazione digitale e collaborativa, con particolare
    riguardo all’ambito contabile, commerciale e al contesto della cooperazione
    internazionale.
baseurl: ""
url: https://botangisi.github.io
github_username: botangisi

theme: minima

show_excerpts: true

supported_languages:
  - en
  - fr
  - it
